# Generated by Django 3.1.7 on 2022-06-30 21:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 6, 30, 21, 2, 3, 983199, tzinfo=utc), help_text='Date Post Created', verbose_name='created AT'),
            preserve_default=False,
        ),
    ]
