# Generated by Django 3.1.7 on 2022-06-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dislikes',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='dislikes Post', null=True, verbose_name='dislikes'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='likes Post', null=True, verbose_name='likes'),
        ),
    ]
